"""
BhuDrishti Backend -- FastAPI application.

Run:
   python -m uvicorn app.main:app --reload --port 8000

All endpoints are documented in /docs (Swagger UI, auto-generated by FastAPI).
Every response includes `"is_demo_data": true` where the data originates
from the synthetic demo dataset, per project instructions.
"""
from __future__ import annotations
<<<<<<< HEAD
from fastapi import FastAPI, HTTPException, Body, UploadFile, File, Form, Query
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from shapely.geometry import mapping, box, Polygon
=======
from fastapi import FastAPI, HTTPException, Body, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from shapely.geometry import mapping, box
>>>>>>> origin/main

from .geometry_engine import Parcel, run_topology_validation, GeometryValidationError
from .elevation_engine import synth_raster_pair, analyze_parcel_elevation
from .confidence_engine import compute_confidence, PRIORITY_THRESHOLDS, priority_for_score
from .demo_data import build_demo_parcels, ELEVATION_DEMO_CONFIG, HISTORICAL_SHIFT_DEMO_M, \
    PROJECT_ID, PROJECT_NAME, CRS, CRS_LABEL
from .verification_store import store, InvalidTransitionError
from . import extraction_engine
from .extraction_store import extraction_store, ExtractionRecord
from .repositories import PERSISTENCE_MODE, PERSISTENCE_LABEL
<<<<<<< HEAD
from pathlib import Path
import sqlite3, json, hashlib
=======
>>>>>>> origin/main

app = FastAPI(
    title="BhuDrishti API",
    description="AI-Powered Urban Cadastral Intelligence Platform -- prototype backend for SIH26012.",
    version="0.1.0-prototype",
)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# ---------------------------------------------------------------------------
# In-memory "database" for the prototype, seeded with the deterministic demo set.
# ---------------------------------------------------------------------------
PARCELS: dict[str, Parcel] = {p.parcel_id: p for p in build_demo_parcels()}
<<<<<<< HEAD
DB_PATH = Path(__file__).resolve().parent.parent / "data" / "bhudrishti.db"
DB_PATH.parent.mkdir(parents=True, exist_ok=True)
UPLOAD_DIR=DB_PATH.parent / "uploads"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

with sqlite3.connect(DB_PATH) as _db:
    _db.execute("""CREATE TABLE IF NOT EXISTS datasets (dataset_id TEXT PRIMARY KEY, filename TEXT, file_type TEXT, size_bytes INTEGER, declared_crs TEXT, status TEXT, created_at TEXT)""")
    _db.commit()
=======
>>>>>>> origin/main


def _authoritative_parcel(parcel_id: str) -> Parcel:
    """Resolve the geometry that downstream GIS/risk/export views should use."""
    base = PARCELS[parcel_id]
    rec = store.get(parcel_id)
    if rec and rec.verified_geometry is not None:
        return Parcel(parcel_id=base.parcel_id, polygon=rec.verified_geometry,
                      source="surveyor_verified", owner=base.owner, ward=base.ward, land_use=base.land_use)
    return base


def _authoritative_parcels() -> list[Parcel]:
    return [_authoritative_parcel(pid) for pid in PARCELS]


def _coordinate_system() -> dict:
    return {"type": "local_demo", "crs": None, "units": "meters", "georeferenced": False,
            "label": CRS_LABEL}


<<<<<<< HEAD
def _candidate_topology_issues(record: ExtractionRecord) -> list[dict]:
    """Analyze every image-derived parcel candidate in pixel space.

    These checks are deliberately scoped to one uploaded image. They are not
    cadastral topology against neighbouring legal parcels because the uploaded
    image has no verified georeferencing in this prototype.
    """
    candidates = record.parcel_candidates or []
    polygons = {}
    issues: list[dict] = []
    for candidate in candidates:
        cid = str(candidate.get("candidate_id") or "")
        pts = candidate.get("pixel_polygon") or []
        try:
            poly = Polygon([(float(x), float(y)) for x, y in pts])
        except Exception:
            poly = None
        if poly is None or poly.is_empty:
            continue
        polygons[cid] = poly
        if not poly.is_valid:
            issues.append({
                "candidate_id": cid,
                "issue_type": "self_intersection",
                "severity": "high",
                "area_px": 0.0,
                "related_candidate_ids": [],
                "description": "Candidate polygon is invalid in image pixel space.",
                "recommended_action": "Surveyor review before accepting the boundary."
            })
    ids = list(polygons)
    for i, a in enumerate(ids):
        for b in ids[i + 1:]:
            pa, pb = polygons[a], polygons[b]
            if pa.intersects(pb):
                inter = pa.intersection(pb)
                if not inter.is_empty and inter.area > 0.5:
                    issues.append({
                        "candidate_id": a,
                        "issue_type": "candidate_overlap",
                        "severity": "medium",
                        "area_px": round(float(inter.area), 2),
                        "related_candidate_ids": [b],
                        "description": f"AI candidate {a} overlaps candidate {b} in image space.",
                        "recommended_action": "Review segmentation and confirm the parcel boundary in the field."
                    })
    return issues


=======
>>>>>>> origin/main

def _irregularity_ratio(p: Parcel) -> float:
    """0 = perfectly matches its minimum bounding rectangle, 1 = highly irregular."""
    if not p.is_valid or p.polygon.area == 0:
        return 1.0
    mrr_area = p.polygon.minimum_rotated_rectangle.area
    if mrr_area == 0:
        return 1.0
    return round(max(0.0, 1.0 - (p.polygon.area / mrr_area)), 3)


def _elevation_for(parcel_id: str):
    cfg = ELEVATION_DEMO_CONFIG[parcel_id]
    dsm, dtm = synth_raster_pair(cfg["seed"], cfg["ground_m"], cfg["height_m"], overhang_px=cfg["overhang_px"])
    return analyze_parcel_elevation(parcel_id, dsm, dtm, overhang_offset_m=cfg["overhang_offset_m"])


def _confidence_for(parcel_id: str, issues_by_parcel: dict):
    p = PARCELS[parcel_id]
    pissues = issues_by_parcel.get(parcel_id, [])
    has_overlap = any(i.issue_type == "overlap" for i in pissues)
    has_gap = any(i.issue_type == "gap" and i.status == "open" for i in pissues)
    has_invalid = any(i.issue_type in ("invalid_geometry", "self_intersection") for i in pissues)
    elev = _elevation_for(parcel_id) if parcel_id in ELEVATION_DEMO_CONFIG else None
    ndsm_dis = abs(elev.overhang_offset_m) if elev else 0.0
    hist_shift = HISTORICAL_SHIFT_DEMO_M.get(parcel_id, 0.0)
    return compute_confidence(
        parcel_id, has_overlap=has_overlap, has_gap=has_gap, has_invalid_geometry=has_invalid,
        irregularity_ratio=_irregularity_ratio(p), ndsm_disagreement_m=ndsm_dis,
        historical_shift_m=hist_shift,
    )


def _issues_by_parcel(issues):
    out: dict[str, list] = {}
    for i in issues:
        for pid in i.parcel_ids:
            out.setdefault(pid, []).append(i)
    return out


def _confidence_for_geometry(pseudo_id: str, polygon_parcel: Parcel, issues_by_parcel: dict):
    """
    Same confidence math as `_confidence_for`, generalized to work on any
    `Parcel` object -- including a freshly generated AI-extraction record
    that is NOT in the seeded `PARCELS` dict and has no synthetic DSM/DTM
    config (extraction records get ndsm_disagreement_m=0.0 and
    historical_shift_m=0.0 -- there is no elevation model or legacy-map
    record for an ad-hoc uploaded image in this prototype).
    """
    pissues = issues_by_parcel.get(pseudo_id, [])
    has_overlap = any(i.issue_type == "overlap" for i in pissues)
    has_gap = any(i.issue_type == "gap" and i.status == "open" for i in pissues)
    has_invalid = any(i.issue_type in ("invalid_geometry", "self_intersection") for i in pissues)
    conf = compute_confidence(
        pseudo_id, has_overlap=has_overlap, has_gap=has_gap, has_invalid_geometry=has_invalid,
        irregularity_ratio=_irregularity_ratio(polygon_parcel), ndsm_disagreement_m=0.0,
        historical_shift_m=0.0,
    )
    # Ad-hoc uploads do not have DSM/DTM or legacy-map context. Keep the
    # primary reason precise instead of implying those datasets were checked.
    if conf.reasons == ["No topology, elevation, or historical conflicts detected"]:
        conf.reasons = [
            "No detected topology issue; elevation and historical comparison are not available for this upload."
        ]
    return conf


# ---------------------------------------------------------------------------
# 1. PROJECTS
# ---------------------------------------------------------------------------
@app.get("/api/projects")
def list_projects():
    return {
        "projects": [{
            "project_id": PROJECT_ID,
            "name": PROJECT_NAME,
            "crs": CRS,
            "coordinate_system": _coordinate_system(),
            "status": "analysis_complete",
            "parcel_count": len(PARCELS),
            "is_demo_data": True,
        }]
    }


@app.get("/api/projects/{project_id}")
def get_project(project_id: str):
    if project_id != PROJECT_ID:
        raise HTTPException(404, "Project not found")
    return {
        "project_id": PROJECT_ID, "name": PROJECT_NAME, "crs": CRS,
        "coordinate_system": _coordinate_system(), "parcel_count": len(PARCELS), "is_demo_data": True,
    }


# ---------------------------------------------------------------------------
# 2. DATASETS (ingestion validation -- prototype-level checks)
# ---------------------------------------------------------------------------
@app.post("/api/datasets/validate")
def validate_dataset(payload: dict = Body(...)):
<<<<<<< HEAD
=======
    """
    Prototype-level ingestion validation. Real production ingestion would
    read actual GeoTIFF/LAS headers via GDAL; this environment has no GDAL,
    so this validates the metadata the frontend uploader already extracts
    (file type, declared CRS, declared extent) and reports pass/fail honestly.
    """
>>>>>>> origin/main
    required = ["file_type", "declared_crs"]
    missing = [k for k in required if k not in payload]
    if missing:
        return {"valid": False, "errors": [f"Missing field: {m}" for m in missing]}
<<<<<<< HEAD
    errors=[]
    if CRS is None and payload.get("declared_crs") not in (None, "", "LOCAL-DEMO"):
        errors.append("CRS validation is unavailable for the local-demo coordinate space.")
    allowed={"geotiff","cog","las","laz","geojson","shapefile","image","orthophoto"}
    if str(payload.get("file_type","")).lower() not in allowed:
        errors.append(f"Unsupported file_type: {payload.get('file_type')}")
    return {"valid": not errors, "errors": errors, "coordinate_system": _coordinate_system()}

@app.post("/api/datasets/upload")
async def upload_dataset(file: UploadFile = File(...), declared_crs: str = Form("LOCAL-DEMO")):
    raw=await file.read()
    ext=Path(file.filename or "upload").suffix.lower().lstrip(".")
    file_type={"tif":"geotiff","tiff":"geotiff","jpg":"image","jpeg":"image","png":"image","geojson":"geojson","las":"las","laz":"laz"}.get(ext,ext or "unknown")
    validation=validate_dataset({"file_type":file_type,"declared_crs":declared_crs})
    if not validation["valid"]: raise HTTPException(422, validation["errors"])
    digest=hashlib.sha1(raw).hexdigest()[:10]
    dataset_id=f"DS-{digest.upper()}"
    from datetime import datetime, timezone
    with sqlite3.connect(DB_PATH) as db:
        (UPLOAD_DIR / dataset_id).write_bytes(raw)
        db.execute("INSERT OR REPLACE INTO datasets VALUES (?,?,?,?,?,?,?)",(dataset_id,file.filename or "upload",file_type,len(raw),declared_crs,"ready",datetime.now(timezone.utc).isoformat()))
        db.commit()
    return {"dataset_id":dataset_id,"filename":file.filename,"file_type":file_type,"size_bytes":len(raw),"status":"ready","validation":validation,"is_demo_data":False}

@app.get("/api/datasets")
def list_datasets():
    with sqlite3.connect(DB_PATH) as db:
        rows=db.execute("SELECT dataset_id,filename,file_type,size_bytes,declared_crs,status,created_at FROM datasets ORDER BY created_at DESC").fetchall()
    keys=["dataset_id","filename","file_type","size_bytes","declared_crs","status","created_at"]
    return {"datasets":[dict(zip(keys,r)) for r in rows],"count":len(rows)}


@app.get("/api/datasets/{dataset_id}/file")
def get_dataset_file(dataset_id: str):
    """Serve the persisted source file so the frontend can display the active dataset.

    This does not replace the authoritative backend inference path; it only lets the
    surveyor see the exact ORI file that was uploaded from Survey Projects.
    """
    with sqlite3.connect(DB_PATH) as db:
        row=db.execute("SELECT filename FROM datasets WHERE dataset_id=?",(dataset_id,)).fetchone()
    path=UPLOAD_DIR / dataset_id
    if not row or not path.exists():
        raise HTTPException(404, "Dataset file not found")
    filename=row[0] or dataset_id
    ext=Path(filename).suffix.lower()
    media={
        ".png":"image/png", ".jpg":"image/jpeg", ".jpeg":"image/jpeg",
        ".webp":"image/webp", ".tif":"image/tiff", ".tiff":"image/tiff",
        ".geojson":"application/geo+json", ".json":"application/json",
    }.get(ext, "application/octet-stream")
    return FileResponse(path, media_type=media, filename=filename)

@app.post("/api/datasets/{dataset_id}/infer")
def infer_dataset(dataset_id: str):
    with sqlite3.connect(DB_PATH) as db:
        row=db.execute("SELECT filename FROM datasets WHERE dataset_id=?",(dataset_id,)).fetchone()
    path=UPLOAD_DIR / dataset_id
    if not row or not path.exists(): raise HTTPException(404,"Dataset not found")
    raw=path.read_bytes()
    try:
        img=extraction_engine.decode_image(raw,row[0] or dataset_id)
        result=extraction_engine.run_cv_inference(img)
    except extraction_engine.ImageDecodeError as e: raise HTTPException(400,f"Image decode error: {e}")
    except extraction_engine.InferenceError as e: raise HTTPException(422,f"Inference could not produce a usable geometry: {e}")
    record=extraction_store.save(ExtractionRecord(extraction_id=extraction_store.new_id(),source_filename=row[0],geometry=result.geometry,image_width=result.image_width,image_height=result.image_height,image_format=result.image_format,confidence_heuristic=result.confidence_heuristic,pixel_polygon=result.pixel_polygon,parcel_candidates=result.parcel_candidates,roof_footprints=result.roof_footprints,inference_mode=result.inference_mode,notes=result.notes,is_demo_data=False,dataset_id=dataset_id))
    return _extraction_response(record)

def _extraction_response(record):
    temp=Parcel(record.extraction_id,record.geometry,source="ai_extraction")
    issues=run_topology_validation([temp]); by=_issues_by_parcel(issues); conf=_confidence_for_geometry(record.extraction_id,temp,by)
    return {**record.to_dict(),"confidence":conf.to_dict(),"topology_issues":[i.to_dict() for i in by.get(record.extraction_id,[])],"topology_issue_count":len(by.get(record.extraction_id,[])),"priority":conf.priority,"compared_against":[],"elevation":None,"elevation_note":"Synthetic elevation can be opened for this extraction as a prototype; no real DEM is attached.","analysis":{"parcel_candidates":record.parcel_candidates,"roof_footprints":record.roof_footprints,"georeferencing":{"available":False,"note":"Uploaded dataset has no verified project georeferencing in this prototype."},"model_adapter":{"current":"opencv_contour_pipeline","future":"segmentation_model","future_implemented":False}}}
=======
    errors = []
    # The bundled prototype geometry is deliberately NOT georeferenced.
    # If a caller supplies a declared CRS, report that this prototype cannot
    # validate it against the local-demo coordinate space.
    if CRS is None and payload.get("declared_crs") not in (None, "", "LOCAL-DEMO"):
        errors.append("This prototype dataset is local-demo geometry and is not georeferenced; CRS validation is unavailable.")
    elif CRS is not None and payload.get("declared_crs") != CRS:
        errors.append(f"CRS mismatch: expected {CRS}, got {payload.get('declared_crs')}")
    allowed_types = {"geotiff", "cog", "las", "laz", "geojson", "shapefile"}
    if str(payload.get("file_type", "")).lower() not in allowed_types:
        errors.append(f"Unsupported file_type: {payload.get('file_type')}")
    return {"valid": len(errors) == 0, "errors": errors}
>>>>>>> origin/main


# ---------------------------------------------------------------------------
# 3. PARCELS
# ---------------------------------------------------------------------------
@app.get("/api/parcels")
def list_parcels():
    authoritative = _authoritative_parcels()
    issues = run_topology_validation(authoritative)
    by_parcel = _issues_by_parcel(issues)
    out = []
    for p in authoritative:
        conf = _confidence_for_geometry(p.parcel_id, p, by_parcel)
        rec = store.get(p.parcel_id)
        out.append({
            "parcel_id": p.parcel_id,
            "geometry": mapping(p.polygon),
            "area_m2": p.area_m2,
            "owner": p.owner,
            "ward": p.ward,
            "land_use": p.land_use,
            "valid_geometry": p.is_valid,
            "confidence": round(conf.confidence, 1),
            "risk_score": round(conf.risk_score, 1),
            "priority": conf.priority,
            "verification_status": rec.status if rec else "unverified",
            "geometry_source": p.source,
            "coordinate_system": p.coordinate_metadata(),
            "is_demo_data": True,
        })
    return {"parcels": out, "count": len(out), "coordinate_system": _coordinate_system()}


@app.get("/api/parcels/{parcel_id}")
def get_parcel(parcel_id: str):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    p = _authoritative_parcel(parcel_id)
    issues = run_topology_validation(_authoritative_parcels())
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for_geometry(parcel_id, p, by_parcel)
    elev = _elevation_for(parcel_id) if parcel_id in ELEVATION_DEMO_CONFIG else None
    rec = store.get(parcel_id)
    return {
        "parcel_id": parcel_id,
        "geometry": mapping(p.polygon),
        "area_m2": p.area_m2,
        "owner": p.owner,
        "ward": p.ward,
        "land_use": p.land_use,
        "valid_geometry": p.is_valid,
        "validity_reason": None if p.is_valid else p.validity_reason,
        "confidence": conf.to_dict(),
        "topology_issues": [i.to_dict() for i in by_parcel.get(parcel_id, [])],
        "elevation": elev.__dict__ if elev else None,
        "verification": rec.to_dict() if rec else None,
        "geometry_source": p.source,
        "coordinate_system": p.coordinate_metadata(),
        "is_demo_data": True,
    }


# ---------------------------------------------------------------------------
# 3b. AI FEATURE EXTRACTION -- PROTOTYPE / SIMULATED
# ---------------------------------------------------------------------------
@app.post("/api/extraction/demo")
def run_demo_extraction(payload: dict = Body(...)):
    """
    PROTOTYPE AI EXTRACTION -- SIMULATED INFERENCE.

    This endpoint does NOT run a real YOLO/segmentation model and there is no
    GPU inference behind it. It maps a selected demo ORI-imagery case onto one
    of the pre-seeded demo parcels that already lives in the same in-memory
    `PARCELS` store used by every other endpoint, and returns that parcel's
    real geometry, confidence, and topology status -- computed the same way
    as `/api/parcels/{id}` -- so downstream screens (GIS map, topology
    validation, survey priority, field verification) receive a single
    consistent, genuine record instead of a fabricated number.

    A production version would replace the case lookup below with real
    raster inference over uploaded drone/ORI imagery (e.g. YOLOv8-Seg +
    vectorization), writing a *new* parcel into the store rather than
    selecting an existing one.
    """
    demo_case = payload.get("demo_case", "BD-047")
    if demo_case not in PARCELS:
        raise HTTPException(404, f"No demo imagery case configured for '{demo_case}'")
    p = PARCELS[demo_case]
    issues = run_topology_validation(list(PARCELS.values()))
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for(demo_case, by_parcel)

    # Detected-feature count is derived from the real polygon vertex count
    # rather than a placeholder, so it moves with the geometry actually used.
    coords = list(p.polygon.exterior.coords) if p.polygon.exterior else []
    detected_feature_count = max(0, len(coords) - 1)

    return {
        "parcel_id": demo_case,
        "geometry": mapping(p.polygon),
        "area_m2": p.area_m2,
        "owner": p.owner,
        "ward": p.ward,
        "detected_feature_count": detected_feature_count,
        "confidence": round(conf.confidence, 1),
        "priority": conf.priority,
        "topology_issue_count": len(by_parcel.get(demo_case, [])),
        "is_demo_data": True,
        "extraction_mode": "PROTOTYPE_SIMULATED",
        "note": "Simulated AI extraction: no YOLO/segmentation model runs in this "
                "prototype. This maps the selected demo imagery case to a "
                "pre-seeded parcel evaluated by the same geometry/confidence "
                "engine used across the rest of the pipeline.",
    }


# ---------------------------------------------------------------------------
# 3c. AI FEATURE EXTRACTION -- REAL, EXECUTABLE IMAGE INFERENCE
# ---------------------------------------------------------------------------
# This is a genuine prototype computer-vision pipeline (see
# extraction_engine.py docstring): PIL decode -> grayscale -> Otsu threshold
# -> morphological cleanup -> OpenCV contour detection -> polygon
# simplification. It is NOT a trained neural model and reports no
# accuracy/mIoU numbers. Geometry is generated fresh from the uploaded
# image's actual pixels -- it is never selected from the PARCELS fixture
# dict, and it is stored in the separate `extraction_store`, not in PARCELS.
@app.post("/api/extraction/infer")
async def infer_extraction(image: UploadFile = File(...)):
    raw = await image.read()
    try:
        img = extraction_engine.decode_image(raw, image.filename or "upload")
        result = extraction_engine.run_cv_inference(img)
    except extraction_engine.ImageDecodeError as e:
        raise HTTPException(400, f"Image decode error: {e}")
    except extraction_engine.InferenceError as e:
        raise HTTPException(422, f"Inference could not produce a usable geometry: {e}")

    record = extraction_store.save(ExtractionRecord(
        extraction_id=extraction_store.new_id(),
        source_filename=image.filename or "upload",
        geometry=result.geometry,
        image_width=result.image_width,
        image_height=result.image_height,
        image_format=result.image_format,
        confidence_heuristic=result.confidence_heuristic,
        pixel_polygon=result.pixel_polygon,
        parcel_candidates=result.parcel_candidates,
        roof_footprints=result.roof_footprints,
        inference_mode=result.inference_mode,
        notes=result.notes,
        is_demo_data=False,
    ))

    # Uploaded prototype images have no georeferencing. Their pixel-derived
    # geometry is therefore NOT in the same spatial reference as the seeded
    # cadastral fixture. Validate the extraction itself (including real GEOS
    # validity) but do not compare it with unrelated parcels or other uploads.
    # This prevents false EXT-vs-EXT / EXT-vs-BD overlap caused only by the
    # shared demo local anchor used by the CV prototype.
    temp_parcel = Parcel(parcel_id=record.extraction_id, polygon=record.geometry,
                          source="ai_extraction", owner=None, ward=None, land_use=None)
    issues = run_topology_validation([temp_parcel])
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for_geometry(record.extraction_id, temp_parcel, by_parcel)
    own_issues = by_parcel.get(record.extraction_id, [])

    return {
        **record.to_dict(),
        "confidence": conf.to_dict(),
        "topology_issues": [i.to_dict() for i in own_issues],
        "topology_issue_count": len(own_issues),
        "priority": conf.priority,
        "compared_against": [],
        "elevation": None,
<<<<<<< HEAD
        "elevation_note": "No real DEM is attached. The Elevation Analysis screen can show a deterministic synthetic prototype surface for this extraction.",
=======
        "elevation_note": "No DSM/DTM exists for ad-hoc image uploads in this prototype; elevation analysis is only available for the seeded demo parcel set.",
>>>>>>> origin/main
        "analysis": {
            "parcel_candidates": record.parcel_candidates,
            "roof_footprints": record.roof_footprints,
            "boundary_comparison": {
                "available": bool(record.roof_footprints),
                "method": "prototype pixel-mask erosion; roof footprint is not a legal cadastral boundary",
                "status": "prototype_inference" if record.roof_footprints else "not_available",
            },
            "georeferencing": {"available": False, "note": "Uploaded image has no embedded project georeferencing in this prototype."},
            "model_adapter": {"current": "opencv_contour_pipeline", "future": "segmentation_model", "future_implemented": False},
<<<<<<< HEAD
            "candidate_topology_issues": _candidate_topology_issues(record),
            "layer_summary": {
                "source_imagery": bool(record.dataset_id),
                "parcel_candidates": len(record.parcel_candidates or []),
                "roof_footprints": len(record.roof_footprints or []),
                "topology_checks": len(_candidate_topology_issues(record)),
            },
=======
>>>>>>> origin/main
        },
    }


@app.get("/api/extraction/{extraction_id}")
def get_extraction(extraction_id: str):
    record = extraction_store.get(extraction_id)
    if not record:
        raise HTTPException(404, "Extraction record not found")
<<<<<<< HEAD
    vr = store.get(record.extraction_id)
    current_geometry = vr.verified_geometry if vr and vr.verified_geometry is not None else record.geometry
    current_source = "surveyor_verified" if vr and vr.verified_geometry is not None else "ai_extraction"
    temp_parcel = Parcel(parcel_id=record.extraction_id, polygon=current_geometry,
                          source=current_source, owner=None, ward=None, land_use=None)
=======
    temp_parcel = Parcel(parcel_id=record.extraction_id, polygon=record.geometry,
                          source="ai_extraction", owner=None, ward=None, land_use=None)
>>>>>>> origin/main
    # No georeferencing is stored for ad-hoc uploads, so only validate this
    # extraction's own geometry. Do not create cross-parcel topology from the
    # prototype's shared local coordinate convention.
    issues = run_topology_validation([temp_parcel])
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for_geometry(record.extraction_id, temp_parcel, by_parcel)
    own_issues = by_parcel.get(record.extraction_id, [])
    return {
        **record.to_dict(),
<<<<<<< HEAD
        "geometry": mapping(current_geometry),
        "area_m2": round(current_geometry.area, 2),
        "status": vr.status if vr else record.status,
        "geometry_source": current_source,
=======
>>>>>>> origin/main
        "confidence": conf.to_dict(),
        "topology_issues": [i.to_dict() for i in own_issues],
        "topology_issue_count": len(own_issues),
        "priority": conf.priority,
        "compared_against": [],
        "elevation": None,
<<<<<<< HEAD
        "elevation_note": "No real DEM is attached. The Elevation Analysis screen can show a deterministic synthetic prototype surface for this extraction.",
        "analysis": {
            "parcel_candidates": record.parcel_candidates,
            "roof_footprints": record.roof_footprints,
            "candidate_topology_issues": _candidate_topology_issues(record),
            "layer_summary": {
                "source_imagery": bool(record.dataset_id),
                "parcel_candidates": len(record.parcel_candidates or []),
                "roof_footprints": len(record.roof_footprints or []),
                "topology_checks": len(_candidate_topology_issues(record)),
            },
=======
        "elevation_note": "No DSM/DTM exists for ad-hoc image uploads in this prototype; elevation analysis is only available for the seeded demo parcel set.",
        "analysis": {
            "parcel_candidates": record.parcel_candidates,
            "roof_footprints": record.roof_footprints,
>>>>>>> origin/main
            "boundary_comparison": {
                "available": bool(record.roof_footprints),
                "method": "prototype pixel-mask erosion; roof footprint is not a legal cadastral boundary",
                "status": "prototype_inference" if record.roof_footprints else "not_available",
            },
            "georeferencing": {"available": False, "note": "Uploaded image has no embedded project georeferencing in this prototype."},
            "model_adapter": {"current": "opencv_contour_pipeline", "future": "segmentation_model", "future_implemented": False},
        },
    }


@app.get("/api/extraction")
def list_extractions():
    return {"extractions": [r.to_dict() for r in extraction_store.all()], "count": len(extraction_store.all())}


# ---------------------------------------------------------------------------
# 4. TOPOLOGY ISSUES
# ---------------------------------------------------------------------------
@app.get("/api/topology/issues")
<<<<<<< HEAD
def list_topology_issues(parcel_id: str | None = Query(None)):
    """Recalculate topology from the current authoritative geometry.

    Seeded BD-* parcels are evaluated together because their local-demo
    spatial relationships are meaningful within the fixture. EXT-* uploads
    are evaluated individually because their pixel-derived local coordinates
    are not georeferenced and therefore must not be compared with seeded or
    unrelated uploads. If parcel_id is supplied, only that record's issues
    are returned.
    """
    seeded = _authoritative_parcels()
    issues = run_topology_validation(seeded)
    ext_ids = {r.extraction_id for r in extraction_store.all()}
    for rec in extraction_store.all():
        vr = store.get(rec.extraction_id)
        geom = vr.verified_geometry if vr and vr.verified_geometry is not None else rec.geometry
        source = "surveyor_verified" if vr and vr.verified_geometry is not None else "ai_extraction"
        issues.extend(run_topology_validation([Parcel(rec.extraction_id, geom, source=source)]))
    if parcel_id:
        if parcel_id in PARCELS:
            issues = [i for i in issues if parcel_id in i.parcel_ids]
        elif parcel_id in ext_ids:
            issues = [i for i in issues if parcel_id in i.parcel_ids]
        else:
            raise HTTPException(404, "Parcel or extraction not found")
    return {
        "issues": [i.to_dict() for i in issues],
        "count": len(issues),
        "coordinate_system": _coordinate_system(),
        "is_demo_data": not any(pid.startswith("EXT-") for i in issues for pid in i.parcel_ids),
        "scope": parcel_id or "all",
    }
=======
def list_topology_issues():
    issues = run_topology_validation(_authoritative_parcels())
    return {"issues": [i.to_dict() for i in issues], "count": len(issues), "coordinate_system": _coordinate_system(), "is_demo_data": True}
>>>>>>> origin/main


# ---------------------------------------------------------------------------
# 5. ELEVATION ANALYSIS
# ---------------------------------------------------------------------------
@app.get("/api/elevation/{parcel_id}")
def get_elevation(parcel_id: str):
<<<<<<< HEAD
    elev=_target_elevation(parcel_id)
    if elev is None: raise HTTPException(404,"No elevation dataset for this parcel")
    return {**elev.__dict__, "is_demo_data": True, "source":"synthetic_demo", "note":"Prototype elevation surface; not a real surveyed DSM/DTM."}
=======
    if parcel_id not in ELEVATION_DEMO_CONFIG:
        raise HTTPException(404, "No elevation dataset for this parcel")
    elev = _elevation_for(parcel_id)
    return {**elev.__dict__, "is_demo_data": True}
>>>>>>> origin/main


# ---------------------------------------------------------------------------
# 6. CONFIDENCE / RISK
# ---------------------------------------------------------------------------
@app.get("/api/confidence/{parcel_id}")
def get_confidence(parcel_id: str):
<<<<<<< HEAD
    if parcel_id in PARCELS:
        p = _authoritative_parcel(parcel_id)
        issues = run_topology_validation(_authoritative_parcels())
        by_parcel = _issues_by_parcel(issues)
        conf = _confidence_for_geometry(parcel_id, p, by_parcel)
        return {**conf.to_dict(), "geometry_source": p.source, "is_demo_data": True}
    if parcel_id.startswith("EXT-"):
        target, _ = _target_geometry(parcel_id)
        if not target:
            raise HTTPException(404, "Extraction record not found")
        issues = run_topology_validation([target])
        by_parcel = _issues_by_parcel(issues)
        conf = _confidence_for_geometry(parcel_id, target, by_parcel)
        rec = extraction_store.get(parcel_id)
        return {**conf.to_dict(), "ai_confidence_heuristic": rec.confidence_heuristic,
                "geometry_source": target.source, "is_demo_data": False,
                "verification_status": store.get(parcel_id).status if store.get(parcel_id) else "unverified"}
    raise HTTPException(404, "Parcel or extraction not found")
=======
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    p = _authoritative_parcel(parcel_id)
    issues = run_topology_validation(_authoritative_parcels())
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for_geometry(parcel_id, p, by_parcel)
    return {**conf.to_dict(), "geometry_source": p.source, "is_demo_data": True}
>>>>>>> origin/main


# ---------------------------------------------------------------------------
# 7. SURVEY PRIORITY QUEUE
# ---------------------------------------------------------------------------
@app.get("/api/survey-queue")
def get_survey_queue():
    # The queue is the single source of truth for ALL priority tiers. Seeded
    # demo parcels use the seeded cadastral spatial context. Ad-hoc uploaded
    # EXT-* records have no georeferencing, so each extraction is evaluated
    # in isolation for geometry validity; it is not treated as a neighboring
    # parcel merely because the prototype CV transform uses a common local
    # coordinate convention.
<<<<<<< HEAD
    extraction_parcels = []
    for r in extraction_store.all():
        vr = store.get(r.extraction_id)
        geom = vr.verified_geometry if vr and vr.verified_geometry is not None else r.geometry
        source = "surveyor_verified" if vr and vr.verified_geometry is not None else "ai_extraction"
        extraction_parcels.append(Parcel(parcel_id=r.extraction_id, polygon=geom, source=source))
=======
    extraction_parcels = [
        Parcel(parcel_id=r.extraction_id, polygon=r.geometry, source="ai_extraction")
        for r in extraction_store.all()
    ]
>>>>>>> origin/main
    authoritative_seeded = _authoritative_parcels()
    seeded_issues = run_topology_validation(authoritative_seeded)
    extraction_issues = []
    for extraction_parcel in extraction_parcels:
        extraction_issues.extend(run_topology_validation([extraction_parcel]))
    issues = seeded_issues + extraction_issues
    by_parcel = _issues_by_parcel(issues)
    ranked = []
    for p in authoritative_seeded:
        pid = p.parcel_id
        conf = _confidence_for_geometry(pid, p, by_parcel)
        rec = store.get(pid)
        ranked.append({
            **conf.to_dict(),
            "is_extraction": False,
            "is_demo_data": True,
            "ai_confidence_heuristic": None,
            "topology_issue_count": len(by_parcel.get(pid, [])),
            "verification_status": rec.status if rec else "unverified",
            "geometry_source": p.source,
        })
    extraction_lookup = {r.extraction_id: r for r in extraction_store.all()}
    for ep in extraction_parcels:
        conf = _confidence_for_geometry(ep.parcel_id, ep, by_parcel)
        rec = extraction_lookup.get(ep.parcel_id)
<<<<<<< HEAD
        vr = store.get(ep.parcel_id)
=======
>>>>>>> origin/main
        # ai_confidence_heuristic surfaces the CV pipeline's OWN quality signal
        # (extraction_engine.run_cv_inference -> ExtractionRecord.confidence_heuristic)
        # alongside -- and clearly distinct from -- the survey/topology-derived
        # `confidence` field above. They measure different things and must not
        # be conflated in the UI: one is "how clean was the image segmentation",
        # the other is "how much does this boundary conflict with the cadastre".
        ranked.append({
            **conf.to_dict(),
            "is_extraction": True,
            "is_demo_data": False,
            "ai_confidence_heuristic": rec.confidence_heuristic if rec else None,
            "topology_issue_count": len(by_parcel.get(ep.parcel_id, [])),
<<<<<<< HEAD
            "verification_status": vr.status if vr else "unverified",
            "geometry_source": ep.source,
=======
>>>>>>> origin/main
        })
    ranked.sort(key=lambda c: c["risk_score"], reverse=True)
    return {
        "thresholds": PRIORITY_THRESHOLDS,
        "queue": ranked,
        "count": len(ranked),
        "high_count": sum(1 for r in ranked if r["priority"] == "high"),
        "medium_count": sum(1 for r in ranked if r["priority"] == "medium"),
        "low_count": sum(1 for r in ranked if r["priority"] == "low"),
        "contains_seeded_demo_data": bool(PARCELS),
        "contains_ai_extractions": bool(extraction_parcels),
    }


# ---------------------------------------------------------------------------
<<<<<<< HEAD
# Cross-screen record resolver
# ---------------------------------------------------------------------------
def _target_geometry(target_id: str):
    if target_id in PARCELS:
        base=PARCELS[target_id]; return base, store.get(target_id)
    if target_id.startswith("EXT-"):
        rec=extraction_store.get(target_id)
        if rec:
            vr=store.get(target_id)
            source_geom=vr.verified_geometry if vr and vr.verified_geometry is not None else rec.geometry
            return Parcel(target_id, source_geom, source="surveyor_verified" if vr and vr.verified_geometry is not None else "ai_extraction"), vr
    return None, None

def _target_elevation(target_id: str):
    if target_id in ELEVATION_DEMO_CONFIG: return _elevation_for(target_id)
    if target_id.startswith("EXT-"):
        rec=extraction_store.get(target_id)
        if rec:
            # Deterministic prototype elevation derived from extracted geometry.
            seed=int(hashlib.sha1(target_id.encode()).hexdigest()[:8],16)
            cfg={"seed":seed,"ground_m":180.0+(seed%300)/100.0,"height_m":2.5+(rec.area_m2%45)/10.0,"overhang_px":0,"overhang_offset_m":0.0}
            dsm,dtm=synth_raster_pair(cfg["seed"],cfg["ground_m"],cfg["height_m"],overhang_px=0)
            return analyze_parcel_elevation(target_id,dsm,dtm,overhang_offset_m=0.0)
    return None

# ---------------------------------------------------------------------------
=======
>>>>>>> origin/main
# 8. VERIFICATION (HITL)
# ---------------------------------------------------------------------------
@app.post("/api/verification/{parcel_id}/submit")
def submit_verification(parcel_id: str, payload: dict = Body(...)):
<<<<<<< HEAD
    target, existing= _target_geometry(parcel_id)
    if not target: raise HTTPException(404,"Parcel or extraction not found")
    geometry=payload.get("geometry")
    if not geometry: raise HTTPException(400,"geometry (GeoJSON) is required")
    try:
        rec=store.submit_correction(parcel_id, target.polygon if existing is None or existing.ai_geometry is None else existing.ai_geometry, geometry, payload.get("surveyor_name","Unknown Surveyor"), payload.get("surveyor_license",""), payload.get("statement",""))
    except GeometryValidationError as e: raise HTTPException(422,f"Geometry validation failed: {e}")
    except InvalidTransitionError as e: raise HTTPException(409,str(e))
    if parcel_id.startswith("EXT-"): extraction_store.update_status(parcel_id,"in_review")
    return {"status":"ok","verification":rec.to_dict()}

@app.post("/api/verification/{parcel_id}/certify")
def certify_verification(parcel_id: str, payload: dict = Body(...)):
    target,existing=_target_geometry(parcel_id)
    if not target: raise HTTPException(404,"Parcel or extraction not found")
    try: rec=store.certify(parcel_id,payload.get("surveyor_name","Unknown Surveyor"))
    except (InvalidTransitionError,KeyError) as e: raise HTTPException(409,str(e))
    if parcel_id.startswith("EXT-"): extraction_store.update_status(parcel_id,"verified")
    return {"status":"ok","verification":rec.to_dict()}

@app.post("/api/verification/{parcel_id}/accept-preliminary")
def accept_preliminary(parcel_id: str, payload: dict = Body(...)):
    target,existing=_target_geometry(parcel_id)
    if not target: raise HTTPException(404,"Parcel or extraction not found")
    try: rec=store.accept_preliminary(parcel_id,target.polygon,payload.get("surveyor_name","Unknown Surveyor"))
    except InvalidTransitionError as e: raise HTTPException(409,str(e))
    if parcel_id.startswith("EXT-"): extraction_store.update_status(parcel_id,"verified")
    return {"status":"ok","verification":rec.to_dict()}

@app.post("/api/verification/{parcel_id}/reject")
def reject_verification(parcel_id: str, payload: dict = Body(...)):
    target,_=_target_geometry(parcel_id)
    if not target: raise HTTPException(404,"Parcel or extraction not found")
    try: rec=store.reject(parcel_id,payload.get("surveyor_name","Unknown Surveyor"),payload.get("reason",""))
    except (InvalidTransitionError,KeyError) as e: raise HTTPException(409,str(e))
    if parcel_id.startswith("EXT-"): extraction_store.update_status(parcel_id,"rejected")
    return {"status":"ok","verification":rec.to_dict()}

@app.get("/api/verification/{parcel_id}")
def get_verification(parcel_id: str):
    target,_=_target_geometry(parcel_id)
    if not target: raise HTTPException(404,"Parcel or extraction not found")
    rec=store.get(parcel_id)
    if not rec: return {"parcel_id":parcel_id,"status":"unverified","audit_trail":[],"ai_geometry":mapping(target.polygon)}
=======
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    geometry = payload.get("geometry")
    surveyor_name = payload.get("surveyor_name", "Unknown Surveyor")
    surveyor_license = payload.get("surveyor_license", "")
    statement = payload.get("statement", "")
    if not geometry:
        raise HTTPException(400, "geometry (GeoJSON) is required")
    try:
        rec = store.submit_correction(parcel_id, PARCELS[parcel_id].polygon, geometry,
                                       surveyor_name, surveyor_license, statement)
    except GeometryValidationError as e:
        # P0-2: invalid/degenerate geometry is rejected with a clear reason
        # instead of being silently accepted into the verification store.
        raise HTTPException(422, f"Geometry validation failed: {e}")
    except InvalidTransitionError as e:
        raise HTTPException(409, str(e))
    return {"status": "ok", "verification": rec.to_dict()}


@app.post("/api/verification/{parcel_id}/certify")
def certify_verification(parcel_id: str, payload: dict = Body(...)):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    surveyor_name = payload.get("surveyor_name", "Unknown Surveyor")
    store.get_or_create(parcel_id, PARCELS[parcel_id].polygon)
    try:
        rec = store.certify(parcel_id, surveyor_name)
    except InvalidTransitionError as e:
        raise HTTPException(409, str(e))
    return {"status": "ok", "verification": rec.to_dict()}


@app.post("/api/verification/{parcel_id}/accept-preliminary")
def accept_preliminary(parcel_id: str, payload: dict = Body(...)):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    surveyor_name = payload.get("surveyor_name", "Unknown Surveyor")
    try:
        rec = store.accept_preliminary(parcel_id, PARCELS[parcel_id].polygon, surveyor_name)
    except InvalidTransitionError as e:
        raise HTTPException(409, str(e))
    return {"status": "ok", "verification": rec.to_dict()}


@app.post("/api/verification/{parcel_id}/reject")
def reject_verification(parcel_id: str, payload: dict = Body(...)):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    surveyor_name = payload.get("surveyor_name", "Unknown Surveyor")
    reason = payload.get("reason", "")
    store.get_or_create(parcel_id, PARCELS[parcel_id].polygon)
    try:
        rec = store.reject(parcel_id, surveyor_name, reason)
    except InvalidTransitionError as e:
        raise HTTPException(409, str(e))
    return {"status": "ok", "verification": rec.to_dict()}


@app.get("/api/verification/{parcel_id}")
def get_verification(parcel_id: str):
    rec = store.get(parcel_id)
    if not rec:
        return {"parcel_id": parcel_id, "status": "unverified", "audit_trail": []}
>>>>>>> origin/main
    return rec.to_dict()


# ---------------------------------------------------------------------------
# 9. EXPORT (uses VERIFIED geometry where present, else AI geometry -- clearly labeled)
# ---------------------------------------------------------------------------
@app.get("/api/export/geojson")
def export_geojson():
<<<<<<< HEAD
    features=[]
    for pid in PARCELS:
        p=_authoritative_parcel(pid); features.append({"type":"Feature","properties":{"parcel_id":pid,"area_m2":round(p.polygon.area,2),"source":p.source,"owner":p.owner,"ward":p.ward},"geometry":mapping(p.polygon)})
    for rec in extraction_store.all():
        target,_=_target_geometry(rec.extraction_id); vr=store.get(rec.extraction_id)
        p=target; features.append({"type":"Feature","properties":{"parcel_id":rec.extraction_id,"area_m2":round(p.polygon.area,2),"source":p.source,"source_filename":rec.source_filename,"verification_status":vr.status if vr else "unverified"},"geometry":mapping(p.polygon)})
    return {"type":"FeatureCollection","crs":None,"coordinate_system":_coordinate_system(),"features":features,"is_demo_data":False,"note":"AI extraction features are preliminary until surveyor verification; verified geometry is exported when available."}
=======
    features = []
    for pid in PARCELS:
        p = _authoritative_parcel(pid)
        geom = p.polygon
        source = p.source
        features.append({
            "type": "Feature",
            "properties": {
                "parcel_id": pid, "area_m2": round(geom.area, 2),
                "source": source, "owner": p.owner, "ward": p.ward,
            },
            "geometry": mapping(geom),
        })
    return {
        "type": "FeatureCollection",
        "crs": None,
        "coordinate_system": _coordinate_system(),
        "features": features,
        "is_demo_data": True,
        "note": "source=ai_preliminary means no surveyor verification has been recorded yet "
                "for that parcel; source=surveyor_verified means a human-certified geometry is used.",
    }
>>>>>>> origin/main


# ---------------------------------------------------------------------------
# 10. DEMO / HEALTH
# ---------------------------------------------------------------------------
@app.get("/api/system/status")
def system_status():
    return {
        "backend": "online",
        "project": PROJECT_ID,
        "extraction": {"mode": "opencv_prototype", "is_demo_data": False, "model": "classical_cv"},
        "elevation": {"mode": "synthetic_demo", "is_demo_data": True},
        "persistence": {"mode": PERSISTENCE_MODE, "label": PERSISTENCE_LABEL},
        "georeferencing": {"mode": "local_demo_coordinates", "crs": None, "georeferenced": False},
        "architecture": {"repository_abstraction": True, "production_storage": "not_connected"},
    }


@app.get("/api/health")
def health():
    return {"status": "ok", "project": PROJECT_ID, "parcel_count": len(PARCELS), "persistence": PERSISTENCE_MODE}


@app.get("/")
def root():
    return {
        "service": "BhuDrishti Backend Prototype",
        "docs": "/docs",
        "endpoints": [
            "/api/projects", "/api/parcels", "/api/parcels/{id}",
            "/api/system/status", "/api/extraction/infer", "/api/extraction/demo", "/api/topology/issues", "/api/elevation/{id}",
            "/api/confidence/{id}", "/api/survey-queue", "/api/verification/{id}",
            "/api/export/geojson",
        ],
    }
