"""
BhuDrishti Backend -- FastAPI application.

Run:
    uvicorn app.main:app --reload --port 8000

All endpoints are documented in /docs (Swagger UI, auto-generated by FastAPI).
Every response includes `"is_demo_data": true` where the data originates
from the synthetic demo dataset, per project instructions.
"""
from __future__ import annotations
from fastapi import FastAPI, HTTPException, Body, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from shapely.geometry import mapping, box

from .geometry_engine import Parcel, run_topology_validation, GeometryValidationError
from .elevation_engine import synth_raster_pair, analyze_parcel_elevation
from .confidence_engine import compute_confidence, PRIORITY_THRESHOLDS, priority_for_score
from .demo_data import build_demo_parcels, ELEVATION_DEMO_CONFIG, HISTORICAL_SHIFT_DEMO_M, \
    PROJECT_ID, PROJECT_NAME, CRS
from .verification_store import store, InvalidTransitionError
from . import extraction_engine
from .extraction_store import extraction_store, ExtractionRecord

app = FastAPI(
    title="BhuDrishti API",
    description="AI-Powered Urban Cadastral Intelligence Platform -- prototype backend for SIH26012.",
    version="0.1.0-prototype",
)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# ---------------------------------------------------------------------------
# In-memory "database" for the prototype, seeded with the deterministic demo set.
# ---------------------------------------------------------------------------
PARCELS: dict[str, Parcel] = {p.parcel_id: p for p in build_demo_parcels()}


def _irregularity_ratio(p: Parcel) -> float:
    """0 = perfectly matches its minimum bounding rectangle, 1 = highly irregular."""
    if not p.is_valid or p.polygon.area == 0:
        return 1.0
    mrr_area = p.polygon.minimum_rotated_rectangle.area
    if mrr_area == 0:
        return 1.0
    return round(max(0.0, 1.0 - (p.polygon.area / mrr_area)), 3)


def _elevation_for(parcel_id: str):
    cfg = ELEVATION_DEMO_CONFIG[parcel_id]
    dsm, dtm = synth_raster_pair(cfg["seed"], cfg["ground_m"], cfg["height_m"], overhang_px=cfg["overhang_px"])
    return analyze_parcel_elevation(parcel_id, dsm, dtm, overhang_offset_m=cfg["overhang_offset_m"])


def _confidence_for(parcel_id: str, issues_by_parcel: dict):
    p = PARCELS[parcel_id]
    pissues = issues_by_parcel.get(parcel_id, [])
    has_overlap = any(i.issue_type == "overlap" for i in pissues)
    has_gap = any(i.issue_type == "gap" and i.status == "open" for i in pissues)
    has_invalid = any(i.issue_type in ("invalid_geometry", "self_intersection") for i in pissues)
    elev = _elevation_for(parcel_id) if parcel_id in ELEVATION_DEMO_CONFIG else None
    ndsm_dis = abs(elev.overhang_offset_m) if elev else 0.0
    hist_shift = HISTORICAL_SHIFT_DEMO_M.get(parcel_id, 0.0)
    return compute_confidence(
        parcel_id, has_overlap=has_overlap, has_gap=has_gap, has_invalid_geometry=has_invalid,
        irregularity_ratio=_irregularity_ratio(p), ndsm_disagreement_m=ndsm_dis,
        historical_shift_m=hist_shift,
    )


def _issues_by_parcel(issues):
    out: dict[str, list] = {}
    for i in issues:
        for pid in i.parcel_ids:
            out.setdefault(pid, []).append(i)
    return out


def _confidence_for_geometry(pseudo_id: str, polygon_parcel: Parcel, issues_by_parcel: dict):
    """
    Same confidence math as `_confidence_for`, generalized to work on any
    `Parcel` object -- including a freshly generated AI-extraction record
    that is NOT in the seeded `PARCELS` dict and has no synthetic DSM/DTM
    config (extraction records get ndsm_disagreement_m=0.0 and
    historical_shift_m=0.0 -- there is no elevation model or legacy-map
    record for an ad-hoc uploaded image in this prototype).
    """
    pissues = issues_by_parcel.get(pseudo_id, [])
    has_overlap = any(i.issue_type == "overlap" for i in pissues)
    has_gap = any(i.issue_type == "gap" and i.status == "open" for i in pissues)
    has_invalid = any(i.issue_type in ("invalid_geometry", "self_intersection") for i in pissues)
    conf = compute_confidence(
        pseudo_id, has_overlap=has_overlap, has_gap=has_gap, has_invalid_geometry=has_invalid,
        irregularity_ratio=_irregularity_ratio(polygon_parcel), ndsm_disagreement_m=0.0,
        historical_shift_m=0.0,
    )
    # Ad-hoc uploads do not have DSM/DTM or legacy-map context. Keep the
    # primary reason precise instead of implying those datasets were checked.
    if conf.reasons == ["No topology, elevation, or historical conflicts detected"]:
        conf.reasons = [
            "No detected topology issue; elevation and historical comparison are not available for this upload."
        ]
    return conf


# ---------------------------------------------------------------------------
# 1. PROJECTS
# ---------------------------------------------------------------------------
@app.get("/api/projects")
def list_projects():
    return {
        "projects": [{
            "project_id": PROJECT_ID,
            "name": PROJECT_NAME,
            "crs": CRS,
            "status": "analysis_complete",
            "parcel_count": len(PARCELS),
            "is_demo_data": True,
        }]
    }


@app.get("/api/projects/{project_id}")
def get_project(project_id: str):
    if project_id != PROJECT_ID:
        raise HTTPException(404, "Project not found")
    return {
        "project_id": PROJECT_ID, "name": PROJECT_NAME, "crs": CRS,
        "parcel_count": len(PARCELS), "is_demo_data": True,
    }


# ---------------------------------------------------------------------------
# 2. DATASETS (ingestion validation -- prototype-level checks)
# ---------------------------------------------------------------------------
@app.post("/api/datasets/validate")
def validate_dataset(payload: dict = Body(...)):
    """
    Prototype-level ingestion validation. Real production ingestion would
    read actual GeoTIFF/LAS headers via GDAL; this environment has no GDAL,
    so this validates the metadata the frontend uploader already extracts
    (file type, declared CRS, declared extent) and reports pass/fail honestly.
    """
    required = ["file_type", "declared_crs"]
    missing = [k for k in required if k not in payload]
    if missing:
        return {"valid": False, "errors": [f"Missing field: {m}" for m in missing]}
    errors = []
    if payload.get("declared_crs") != CRS:
        errors.append(f"CRS mismatch: expected {CRS}, got {payload.get('declared_crs')}")
    allowed_types = {"geotiff", "cog", "las", "laz", "geojson", "shapefile"}
    if str(payload.get("file_type", "")).lower() not in allowed_types:
        errors.append(f"Unsupported file_type: {payload.get('file_type')}")
    return {"valid": len(errors) == 0, "errors": errors}


# ---------------------------------------------------------------------------
# 3. PARCELS
# ---------------------------------------------------------------------------
@app.get("/api/parcels")
def list_parcels():
    issues = run_topology_validation(list(PARCELS.values()))
    by_parcel = _issues_by_parcel(issues)
    out = []
    for pid, p in PARCELS.items():
        conf = _confidence_for(pid, by_parcel)
        rec = store.get(pid)
        out.append({
            "parcel_id": pid,
            "area_m2": p.area_m2,
            "owner": p.owner,
            "ward": p.ward,
            "valid_geometry": p.is_valid,
            "confidence": round(conf.confidence, 1),
            "priority": conf.priority,
            "verification_status": rec.status if rec else "unverified",
            "is_demo_data": True,
        })
    return {"parcels": out, "count": len(out)}


@app.get("/api/parcels/{parcel_id}")
def get_parcel(parcel_id: str):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    p = PARCELS[parcel_id]
    issues = run_topology_validation(list(PARCELS.values()))
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for(parcel_id, by_parcel)
    elev = _elevation_for(parcel_id) if parcel_id in ELEVATION_DEMO_CONFIG else None
    rec = store.get(parcel_id)
    return {
        "parcel_id": parcel_id,
        "geometry": mapping(p.polygon),
        "area_m2": p.area_m2,
        "owner": p.owner,
        "ward": p.ward,
        "land_use": p.land_use,
        "valid_geometry": p.is_valid,
        "validity_reason": None if p.is_valid else p.validity_reason,
        "confidence": conf.to_dict(),
        "topology_issues": [i.to_dict() for i in by_parcel.get(parcel_id, [])],
        "elevation": elev.__dict__ if elev else None,
        "verification": rec.to_dict() if rec else None,
        "is_demo_data": True,
    }


# ---------------------------------------------------------------------------
# 3b. AI FEATURE EXTRACTION -- PROTOTYPE / SIMULATED
# ---------------------------------------------------------------------------
@app.post("/api/extraction/demo")
def run_demo_extraction(payload: dict = Body(...)):
    """
    PROTOTYPE AI EXTRACTION -- SIMULATED INFERENCE.

    This endpoint does NOT run a real YOLO/segmentation model and there is no
    GPU inference behind it. It maps a selected demo ORI-imagery case onto one
    of the pre-seeded demo parcels that already lives in the same in-memory
    `PARCELS` store used by every other endpoint, and returns that parcel's
    real geometry, confidence, and topology status -- computed the same way
    as `/api/parcels/{id}` -- so downstream screens (GIS map, topology
    validation, survey priority, field verification) receive a single
    consistent, genuine record instead of a fabricated number.

    A production version would replace the case lookup below with real
    raster inference over uploaded drone/ORI imagery (e.g. YOLOv8-Seg +
    vectorization), writing a *new* parcel into the store rather than
    selecting an existing one.
    """
    demo_case = payload.get("demo_case", "BD-047")
    if demo_case not in PARCELS:
        raise HTTPException(404, f"No demo imagery case configured for '{demo_case}'")
    p = PARCELS[demo_case]
    issues = run_topology_validation(list(PARCELS.values()))
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for(demo_case, by_parcel)

    # Detected-feature count is derived from the real polygon vertex count
    # rather than a placeholder, so it moves with the geometry actually used.
    coords = list(p.polygon.exterior.coords) if p.polygon.exterior else []
    detected_feature_count = max(0, len(coords) - 1)

    return {
        "parcel_id": demo_case,
        "geometry": mapping(p.polygon),
        "area_m2": p.area_m2,
        "owner": p.owner,
        "ward": p.ward,
        "detected_feature_count": detected_feature_count,
        "confidence": round(conf.confidence, 1),
        "priority": conf.priority,
        "topology_issue_count": len(by_parcel.get(demo_case, [])),
        "is_demo_data": True,
        "extraction_mode": "PROTOTYPE_SIMULATED",
        "note": "Simulated AI extraction: no YOLO/segmentation model runs in this "
                "prototype. This maps the selected demo imagery case to a "
                "pre-seeded parcel evaluated by the same geometry/confidence "
                "engine used across the rest of the pipeline.",
    }


# ---------------------------------------------------------------------------
# 3c. AI FEATURE EXTRACTION -- REAL, EXECUTABLE IMAGE INFERENCE
# ---------------------------------------------------------------------------
# This is a genuine prototype computer-vision pipeline (see
# extraction_engine.py docstring): PIL decode -> grayscale -> Otsu threshold
# -> morphological cleanup -> OpenCV contour detection -> polygon
# simplification. It is NOT a trained neural model and reports no
# accuracy/mIoU numbers. Geometry is generated fresh from the uploaded
# image's actual pixels -- it is never selected from the PARCELS fixture
# dict, and it is stored in the separate `extraction_store`, not in PARCELS.
@app.post("/api/extraction/infer")
async def infer_extraction(image: UploadFile = File(...)):
    raw = await image.read()
    try:
        img = extraction_engine.decode_image(raw, image.filename or "upload")
        result = extraction_engine.run_cv_inference(img)
    except extraction_engine.ImageDecodeError as e:
        raise HTTPException(400, f"Image decode error: {e}")
    except extraction_engine.InferenceError as e:
        raise HTTPException(422, f"Inference could not produce a usable geometry: {e}")

    record = extraction_store.save(ExtractionRecord(
        extraction_id=extraction_store.new_id(),
        source_filename=image.filename or "upload",
        geometry=result.geometry,
        image_width=result.image_width,
        image_height=result.image_height,
        image_format=result.image_format,
        confidence_heuristic=result.confidence_heuristic,
        pixel_polygon=result.pixel_polygon,
        inference_mode=result.inference_mode,
        notes=result.notes,
        is_demo_data=False,
    ))

    # Uploaded prototype images have no georeferencing. Their pixel-derived
    # geometry is therefore NOT in the same spatial reference as the seeded
    # cadastral fixture. Validate the extraction itself (including real GEOS
    # validity) but do not compare it with unrelated parcels or other uploads.
    # This prevents false EXT-vs-EXT / EXT-vs-BD overlap caused only by the
    # shared demo local anchor used by the CV prototype.
    temp_parcel = Parcel(parcel_id=record.extraction_id, polygon=record.geometry,
                          source="ai_extraction", owner=None, ward=None, land_use=None)
    issues = run_topology_validation([temp_parcel])
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for_geometry(record.extraction_id, temp_parcel, by_parcel)
    own_issues = by_parcel.get(record.extraction_id, [])

    return {
        **record.to_dict(),
        "confidence": conf.to_dict(),
        "topology_issues": [i.to_dict() for i in own_issues],
        "topology_issue_count": len(own_issues),
        "priority": conf.priority,
        "compared_against": [],
        "elevation": None,
        "elevation_note": "No DSM/DTM exists for ad-hoc image uploads in this prototype; "
                           "elevation analysis is only available for the seeded demo parcel set.",
    }


@app.get("/api/extraction/{extraction_id}")
def get_extraction(extraction_id: str):
    record = extraction_store.get(extraction_id)
    if not record:
        raise HTTPException(404, "Extraction record not found")
    temp_parcel = Parcel(parcel_id=record.extraction_id, polygon=record.geometry,
                          source="ai_extraction", owner=None, ward=None, land_use=None)
    # No georeferencing is stored for ad-hoc uploads, so only validate this
    # extraction's own geometry. Do not create cross-parcel topology from the
    # prototype's shared local coordinate convention.
    issues = run_topology_validation([temp_parcel])
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for_geometry(record.extraction_id, temp_parcel, by_parcel)
    own_issues = by_parcel.get(record.extraction_id, [])
    return {
        **record.to_dict(),
        "confidence": conf.to_dict(),
        "topology_issues": [i.to_dict() for i in own_issues],
        "topology_issue_count": len(own_issues),
        "priority": conf.priority,
        "compared_against": [],
        "elevation": None,
        "elevation_note": "No DSM/DTM exists for ad-hoc image uploads in this prototype; "
                           "elevation analysis is only available for the seeded demo parcel set.",
    }


@app.get("/api/extraction")
def list_extractions():
    return {"extractions": [r.to_dict() for r in extraction_store.all()], "count": len(extraction_store.all())}


# ---------------------------------------------------------------------------
# 4. TOPOLOGY ISSUES
# ---------------------------------------------------------------------------
@app.get("/api/topology/issues")
def list_topology_issues():
    issues = run_topology_validation(list(PARCELS.values()))
    return {"issues": [i.to_dict() for i in issues], "count": len(issues), "is_demo_data": True}


# ---------------------------------------------------------------------------
# 5. ELEVATION ANALYSIS
# ---------------------------------------------------------------------------
@app.get("/api/elevation/{parcel_id}")
def get_elevation(parcel_id: str):
    if parcel_id not in ELEVATION_DEMO_CONFIG:
        raise HTTPException(404, "No elevation dataset for this parcel")
    elev = _elevation_for(parcel_id)
    return {**elev.__dict__, "is_demo_data": True}


# ---------------------------------------------------------------------------
# 6. CONFIDENCE / RISK
# ---------------------------------------------------------------------------
@app.get("/api/confidence/{parcel_id}")
def get_confidence(parcel_id: str):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    issues = run_topology_validation(list(PARCELS.values()))
    by_parcel = _issues_by_parcel(issues)
    conf = _confidence_for(parcel_id, by_parcel)
    return {**conf.to_dict(), "is_demo_data": True}


# ---------------------------------------------------------------------------
# 7. SURVEY PRIORITY QUEUE
# ---------------------------------------------------------------------------
@app.get("/api/survey-queue")
def get_survey_queue():
    # The queue is the single source of truth for ALL priority tiers. Seeded
    # demo parcels use the seeded cadastral spatial context. Ad-hoc uploaded
    # EXT-* records have no georeferencing, so each extraction is evaluated
    # in isolation for geometry validity; it is not treated as a neighboring
    # parcel merely because the prototype CV transform uses a common local
    # coordinate convention.
    extraction_parcels = [
        Parcel(parcel_id=r.extraction_id, polygon=r.geometry, source="ai_extraction")
        for r in extraction_store.all()
    ]
    seeded_issues = run_topology_validation(list(PARCELS.values()))
    extraction_issues = []
    for extraction_parcel in extraction_parcels:
        extraction_issues.extend(run_topology_validation([extraction_parcel]))
    issues = seeded_issues + extraction_issues
    by_parcel = _issues_by_parcel(issues)
    ranked = []
    for pid in PARCELS:
        conf = _confidence_for(pid, by_parcel)
        ranked.append({
            **conf.to_dict(),
            "is_extraction": False,
            "is_demo_data": True,
            "ai_confidence_heuristic": None,
            "topology_issue_count": len(by_parcel.get(pid, [])),
        })
    extraction_lookup = {r.extraction_id: r for r in extraction_store.all()}
    for ep in extraction_parcels:
        conf = _confidence_for_geometry(ep.parcel_id, ep, by_parcel)
        rec = extraction_lookup.get(ep.parcel_id)
        # ai_confidence_heuristic surfaces the CV pipeline's OWN quality signal
        # (extraction_engine.run_cv_inference -> ExtractionRecord.confidence_heuristic)
        # alongside -- and clearly distinct from -- the survey/topology-derived
        # `confidence` field above. They measure different things and must not
        # be conflated in the UI: one is "how clean was the image segmentation",
        # the other is "how much does this boundary conflict with the cadastre".
        ranked.append({
            **conf.to_dict(),
            "is_extraction": True,
            "is_demo_data": False,
            "ai_confidence_heuristic": rec.confidence_heuristic if rec else None,
            "topology_issue_count": len(by_parcel.get(ep.parcel_id, [])),
        })
    ranked.sort(key=lambda c: c["risk_score"], reverse=True)
    return {
        "thresholds": PRIORITY_THRESHOLDS,
        "queue": ranked,
        "count": len(ranked),
        "high_count": sum(1 for r in ranked if r["priority"] == "high"),
        "medium_count": sum(1 for r in ranked if r["priority"] == "medium"),
        "low_count": sum(1 for r in ranked if r["priority"] == "low"),
        "contains_seeded_demo_data": bool(PARCELS),
        "contains_ai_extractions": bool(extraction_parcels),
    }


# ---------------------------------------------------------------------------
# 8. VERIFICATION (HITL)
# ---------------------------------------------------------------------------
@app.post("/api/verification/{parcel_id}/submit")
def submit_verification(parcel_id: str, payload: dict = Body(...)):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    geometry = payload.get("geometry")
    surveyor_name = payload.get("surveyor_name", "Unknown Surveyor")
    surveyor_license = payload.get("surveyor_license", "")
    statement = payload.get("statement", "")
    if not geometry:
        raise HTTPException(400, "geometry (GeoJSON) is required")
    try:
        rec = store.submit_correction(parcel_id, PARCELS[parcel_id].polygon, geometry,
                                       surveyor_name, surveyor_license, statement)
    except GeometryValidationError as e:
        # P0-2: invalid/degenerate geometry is rejected with a clear reason
        # instead of being silently accepted into the verification store.
        raise HTTPException(422, f"Geometry validation failed: {e}")
    except InvalidTransitionError as e:
        raise HTTPException(409, str(e))
    return {"status": "ok", "verification": rec.to_dict()}


@app.post("/api/verification/{parcel_id}/certify")
def certify_verification(parcel_id: str, payload: dict = Body(...)):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    surveyor_name = payload.get("surveyor_name", "Unknown Surveyor")
    store.get_or_create(parcel_id, PARCELS[parcel_id].polygon)
    try:
        rec = store.certify(parcel_id, surveyor_name)
    except InvalidTransitionError as e:
        raise HTTPException(409, str(e))
    return {"status": "ok", "verification": rec.to_dict()}


@app.post("/api/verification/{parcel_id}/accept-preliminary")
def accept_preliminary(parcel_id: str, payload: dict = Body(...)):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    surveyor_name = payload.get("surveyor_name", "Unknown Surveyor")
    try:
        rec = store.accept_preliminary(parcel_id, PARCELS[parcel_id].polygon, surveyor_name)
    except InvalidTransitionError as e:
        raise HTTPException(409, str(e))
    return {"status": "ok", "verification": rec.to_dict()}


@app.post("/api/verification/{parcel_id}/reject")
def reject_verification(parcel_id: str, payload: dict = Body(...)):
    if parcel_id not in PARCELS:
        raise HTTPException(404, "Parcel not found")
    surveyor_name = payload.get("surveyor_name", "Unknown Surveyor")
    reason = payload.get("reason", "")
    store.get_or_create(parcel_id, PARCELS[parcel_id].polygon)
    try:
        rec = store.reject(parcel_id, surveyor_name, reason)
    except InvalidTransitionError as e:
        raise HTTPException(409, str(e))
    return {"status": "ok", "verification": rec.to_dict()}


@app.get("/api/verification/{parcel_id}")
def get_verification(parcel_id: str):
    rec = store.get(parcel_id)
    if not rec:
        return {"parcel_id": parcel_id, "status": "unverified", "audit_trail": []}
    return rec.to_dict()


# ---------------------------------------------------------------------------
# 9. EXPORT (uses VERIFIED geometry where present, else AI geometry -- clearly labeled)
# ---------------------------------------------------------------------------
@app.get("/api/export/geojson")
def export_geojson():
    features = []
    for pid, p in PARCELS.items():
        rec = store.get(pid)
        if rec and rec.verified_geometry is not None:
            geom = rec.verified_geometry
            source = "surveyor_verified"
        else:
            geom = p.polygon
            source = "ai_preliminary"
        features.append({
            "type": "Feature",
            "properties": {
                "parcel_id": pid, "area_m2": round(geom.area, 2),
                "source": source, "owner": p.owner, "ward": p.ward,
            },
            "geometry": mapping(geom),
        })
    return {
        "type": "FeatureCollection",
        "crs": {"type": "name", "properties": {"name": CRS}},
        "features": features,
        "is_demo_data": True,
        "note": "source=ai_preliminary means no surveyor verification has been recorded yet "
                "for that parcel; source=surveyor_verified means a human-certified geometry is used.",
    }


# ---------------------------------------------------------------------------
# 10. DEMO / HEALTH
# ---------------------------------------------------------------------------
@app.get("/api/health")
def health():
    return {"status": "ok", "project": PROJECT_ID, "parcel_count": len(PARCELS)}


@app.get("/")
def root():
    return {
        "service": "BhuDrishti Backend Prototype",
        "docs": "/docs",
        "endpoints": [
            "/api/projects", "/api/parcels", "/api/parcels/{id}",
            "/api/extraction/demo", "/api/topology/issues", "/api/elevation/{id}",
            "/api/confidence/{id}", "/api/survey-queue", "/api/verification/{id}",
            "/api/export/geojson",
        ],
    }
